#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.go$")

function lint() {
  # only lint if Go files have changed
  if [ ! -z "$STAGED_GO_FILES" ]; then
    make lint
  fi
}

function secretsscan() {
  gitleaks git -v --staged
}

# inform about failed pre-commit hook
function failed {
  echo ''
  echo -e "pre-commit hook failed... You can not push!"
  echo ''

  exit 1
}

trap 'failed' ERR

lint
secretsscan
