#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.go$")

function lint() {
  # only lint if Go files have changed
  if [ ! -z "$STAGED_GO_FILES" ]; then
    make lint
  fi
}

# inform about failed pre-push hook
function failed {
  echo ''
  echo -e "pre-push hook failed... You cannot push!"
  echo ''

  exit 1
}

trap 'failed' ERR

lint
