// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ak/ak.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/ak/ak.go -package=mock_ak -source=internal/ak/ak.go
//

// Package mock_ak is a generated GoMock package.
package mock_ak

import (
	reflect "reflect"

	ak "github.com/svetlyopet/authentik-cli/internal/ak"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthentikRepository is a mock of AuthentikRepository interface.
type MockAuthentikRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthentikRepositoryMockRecorder
}

// MockAuthentikRepositoryMockRecorder is the mock recorder for MockAuthentikRepository.
type MockAuthentikRepositoryMockRecorder struct {
	mock *MockAuthentikRepository
}

// NewMockAuthentikRepository creates a new mock instance.
func NewMockAuthentikRepository(ctrl *gomock.Controller) *MockAuthentikRepository {
	mock := &MockAuthentikRepository{ctrl: ctrl}
	mock.recorder = &MockAuthentikRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthentikRepository) EXPECT() *MockAuthentikRepositoryMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockAuthentikRepository) AddUserToGroup(userPK int, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", userPK, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockAuthentikRepositoryMockRecorder) AddUserToGroup(userPK, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockAuthentikRepository)(nil).AddUserToGroup), userPK, uuid)
}

// AssignViewPermissionsToTenantRole mocks base method.
func (m *MockAuthentikRepository) AssignViewPermissionsToTenantRole(rolePK string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignViewPermissionsToTenantRole", rolePK)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignViewPermissionsToTenantRole indicates an expected call of AssignViewPermissionsToTenantRole.
func (mr *MockAuthentikRepositoryMockRecorder) AssignViewPermissionsToTenantRole(rolePK any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignViewPermissionsToTenantRole", reflect.TypeOf((*MockAuthentikRepository)(nil).AssignViewPermissionsToTenantRole), rolePK)
}

// CreateGroup mocks base method.
func (m *MockAuthentikRepository) CreateGroup(name string, roles []string, attributes ak.GroupAttributes) (*ak.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", name, roles, attributes)
	ret0, _ := ret[0].(*ak.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockAuthentikRepositoryMockRecorder) CreateGroup(name, roles, attributes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockAuthentikRepository)(nil).CreateGroup), name, roles, attributes)
}

// CreateRole mocks base method.
func (m *MockAuthentikRepository) CreateRole(name string) (*ak.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", name)
	ret0, _ := ret[0].(*ak.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAuthentikRepositoryMockRecorder) CreateRole(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAuthentikRepository)(nil).CreateRole), name)
}

// CreateUser mocks base method.
func (m *MockAuthentikRepository) CreateUser(usr ak.User) (*ak.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", usr)
	ret0, _ := ret[0].(*ak.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthentikRepositoryMockRecorder) CreateUser(usr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthentikRepository)(nil).CreateUser), usr)
}

// DeleteGroup mocks base method.
func (m *MockAuthentikRepository) DeleteGroup(uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockAuthentikRepositoryMockRecorder) DeleteGroup(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockAuthentikRepository)(nil).DeleteGroup), uuid)
}

// DeleteRole mocks base method.
func (m *MockAuthentikRepository) DeleteRole(uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAuthentikRepositoryMockRecorder) DeleteRole(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAuthentikRepository)(nil).DeleteRole), uuid)
}

// DeleteUser mocks base method.
func (m *MockAuthentikRepository) DeleteUser(userPK string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userPK)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAuthentikRepositoryMockRecorder) DeleteUser(userPK any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAuthentikRepository)(nil).DeleteUser), userPK)
}

// GetGroupByName mocks base method.
func (m *MockAuthentikRepository) GetGroupByName(name string) (*ak.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", name)
	ret0, _ := ret[0].(*ak.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockAuthentikRepositoryMockRecorder) GetGroupByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockAuthentikRepository)(nil).GetGroupByName), name)
}

// GetRoleByName mocks base method.
func (m *MockAuthentikRepository) GetRoleByName(name string) (*ak.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", name)
	ret0, _ := ret[0].(*ak.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockAuthentikRepositoryMockRecorder) GetRoleByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockAuthentikRepository)(nil).GetRoleByName), name)
}

// GetUserByUsername mocks base method.
func (m *MockAuthentikRepository) GetUserByUsername(username string) (*ak.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", username)
	ret0, _ := ret[0].(*ak.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockAuthentikRepositoryMockRecorder) GetUserByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockAuthentikRepository)(nil).GetUserByUsername), username)
}
