name: authentik-cli-ci-main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint-golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  test-unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Run unit tests
      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

  test-integrationtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Create e2e env
      run: ./ci/integration_tests/ak_bootstrap.sh create
      env:
        AK_BOOTSTRAP_CI: "true"
        AK_BOOTSTRAP_WAIT: "90"

    - name: Run e2e tests
      run: ./ci/integration_tests/ak_run_e2e.sh

    - name: Destroy e2e env
      run: ./ci/integration_tests/ak_bootstrap.sh destroy
