name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run build
      run: go build -o bin/ak .

    - name: Run unit tests
      run: go test -v ./...

    - name: Create e2e env
      run: ./ci/integration_tests/ak_bootstrap.sh create

    - name: Run e2e tests
      run: ./ci/integration_tests/ak_run_e2e.sh

    - name: Cleanup e2e env
      run: ./ci/integration_tests/ak_bootstrap.sh destroy
